/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capapresentacion;


/**
 *
 * @author valie
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mantenimiento = new javax.swing.JMenu();
        frmMantenimientoactivo = new javax.swing.JMenuItem();
        RegistroVentas = new javax.swing.JMenu();
        frmRegistroVenta = new javax.swing.JMenuItem();
        frmCliente = new javax.swing.JMenuItem();
        frmVendedor = new javax.swing.JMenuItem();
        frmAutomovil = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        Mantenimiento.setText("Mantenimiento");
        Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenimientoActionPerformed(evt);
            }
        });

        frmMantenimientoactivo.setText("Mantenimiento");
        frmMantenimientoactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmMantenimientoactivoActionPerformed(evt);
            }
        });
        Mantenimiento.add(frmMantenimientoactivo);

        jMenuBar1.add(Mantenimiento);

        RegistroVentas.setText("Registro de ventas");

        frmRegistroVenta.setText("Registro de Ventas");
        frmRegistroVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmRegistroVentaActionPerformed(evt);
            }
        });
        RegistroVentas.add(frmRegistroVenta);

        frmCliente.setText("Cliente");
        frmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmClienteActionPerformed(evt);
            }
        });
        RegistroVentas.add(frmCliente);

        frmVendedor.setText("Vendedor");
        frmVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmVendedorActionPerformed(evt);
            }
        });
        RegistroVentas.add(frmVendedor);

        frmAutomovil.setText("Automovil");
        frmAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmAutomovilActionPerformed(evt);
            }
        });
        RegistroVentas.add(frmAutomovil);

        jMenuBar1.add(RegistroVentas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmClienteActionPerformed
        frmCliente verventana = new frmCliente ();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_frmClienteActionPerformed

    private void frmVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmVendedorActionPerformed
        frmVendedor verventana = new frmVendedor ();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_frmVendedorActionPerformed

    private void MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenimientoActionPerformed
        frmMantenimiento verventana = new frmMantenimiento ();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_MantenimientoActionPerformed

    private void frmRegistroVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmRegistroVentaActionPerformed
        frmRegistroVenta verventana = new frmRegistroVenta ();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_frmRegistroVentaActionPerformed

    private void frmAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmAutomovilActionPerformed
        frmAutomovil verventana = new frmAutomovil ();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_frmAutomovilActionPerformed

    private void frmMantenimientoactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmMantenimientoactivoActionPerformed
        frmMantenimiento verventana = new frmMantenimiento ();
        escritorio.add(verventana);
        verventana.show();
    }//GEN-LAST:event_frmMantenimientoactivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Mantenimiento;
    private javax.swing.JMenu RegistroVentas;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem frmAutomovil;
    private javax.swing.JMenuItem frmCliente;
    private javax.swing.JMenuItem frmMantenimientoactivo;
    private javax.swing.JMenuItem frmRegistroVenta;
    private javax.swing.JMenuItem frmVendedor;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
